version: "3"
services:
  web:
    container_name: djangosqs
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    env_file:
      - .env
  celery:
    container_name: djangosqscel
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: celery -A django_sqs_cel worker --beat --scheduler django --loglevel=info -Q TestSqs
    env_file:
      - .env